# Generated by Django 6.1.1 on 2026-09-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bank_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cgpa_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='login_link',
            field=models.URLField(blank=True),
        ),
    ]
