# Generated by Django 6.1.1 on 2026-09-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_learning',
            field=models.BooleanField(default=False),
        ),
    ]
